version: 2
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    pre_install:
      - python -m pip install --upgrade pip
      - python -m pip install uv
      - uv export --group docs --format requirements.txt --frozen --no-hashes --output /tmp/requirements-docs.txt
      - python -m pip install -r /tmp/requirements-docs.txt
formats: all
