version: 2
sphinx:
  configuration: docs/source/conf.py
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
