{% set setup_py = load_setup_py_data() %}

package:
    name: 'stats_can'
    version: {{ setup_py.get('version') }}

source:
    path: ./

build:
    noarch: python
    number: 1
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    run:
        - python 3
        - pandas >=0.23
        - numpy >=1.15
        - requests >=2.19
        - h5py >= 2.8.0
        - pytables >= 3.4.4
    build:
        - python 3
        - setuptools

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}
