name: Coverage
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v27
    - run: nix develop . -c coverage run -m pytest
    - run: nix develop . coverage combine
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
