name: Coverage
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: x64
    - run: pip install nox==2023.04.22
    - run: pip install nox-poetry==1.0.3
    - run: pip install poetry==1.8.2
    - run: nox --sessions tests-3.11 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
