name: Coverage
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: x64
    - run: pip install nox==2022.11.21
    - run: pip install nox-poetry==1.0.2
    - run: pip install poetry==1.3.1
    - run: nox --sessions tests-3.10 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
