name: PyPi
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'src/**'
      - 'pyproject.toml'
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No build required" '
