name: Tests
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: make test
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
