name: Tests
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.9', '3.8']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install nox==2021.10.1
    - run: pip install nox-poetry==0.9.0
    - run: pip install poetry==1.1.12
    - run: nox --python ${{ matrix.python-version }}
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
